FROM php:8.3.3-apache-bookworm
LABEL maintainer="Maximilian Riedel (m.riedel.1998@t-online.de)"
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install pdo_mysql
RUN apt-get update && apt-get upgrade -y
RUN apt-get install zlib1g-dev -y
RUN apt-get install libpng-dev -y
RUN docker-php-ext-install gd
RUN a2enmod rewrite
EXPOSE 80
EXPOSE 443